#!/bin/bash
RED="\033[1;31m"
GREEN="\033[1;32m"
NC="\033[0m"

function remove_last_char_if_not_empty() {
	container=("$@")
	if [[ -n "$container" ]]
	then
		container=${container::-1}
	fi
	echo "$container"
}

function create_pattern() {
    files_paths_list=("$@")
    pattern=""
    for file_name in $files_paths_list
    do
        pattern="${pattern}${file_name}|"
    done
    pattern=$(remove_last_char_if_not_empty "${pattern[*]}")
    echo "$pattern"
}

function filter_array_with_inverted_regEx() {
	files_paths_list=("$@")
	query=$2
	container=""
	if [[ -z "${query}" ]]
    then
        container=$files_paths_list
	else
        for value in $files_paths_list
        do
            matched_string=$(echo "$value" | grep -v -E "$query")
            if [[ -n "$matched_string" ]]
            then
                container="${container}${value} "
            fi
        done
        container=$(remove_last_char_if_not_empty "${container[*]}")
    fi
	echo "$container"
}

function add_files_to_staged_tree() {
	files_paths=("$@")
		if [[ -n "${files_paths// }" ]]
    then
        git add $files_paths
    fi
}

eslint_autofix_flag=""
stylelint_autofix_flag=""
eslint_exit_code=0
stylelint_exit_code=0
not_staged_ts_files=$(git diff --diff-filter=b --name-only | grep .ts$)
not_staged_scss_files=$(git diff --diff-filter=b --name-only | grep .scss$)
staged_ts_files=$(git diff --cached --diff-filter=d --name-only | grep .ts$)
staged_scss_files=$(git diff --cached --diff-filter=d --name-only | grep .scss$)
ts_filter_regex=$(create_pattern "${not_staged_ts_files[*]}")
scss_filter_regex=$(create_pattern "${not_staged_scss_files[*]}")
ts_files_to_add_after_linting=$(filter_array_with_inverted_regEx "${staged_ts_files[*]}" "${ts_filter_regex}")
scss_files_to_add_after_linting=$(filter_array_with_inverted_regEx "${staged_scss_files[*]}" "${scss_filter_regex}")

if [ ${#ts_files_to_add_after_linting} = ${#staged_ts_files} ]
then
	eslint_autofix_flag="--fix"
fi
if [ ${#scss_files_to_add_after_linting} = ${#staged_scss_files} ]
then
	stylelint_autofix_flag="--fix"
fi
if [[ -n "$staged_ts_files" ]]
then
    echo "Running ESLint..."
    ./node_modules/.bin/eslint $staged_ts_files --quiet $eslint_autofix_flag
    eslint_exit_code=$?
fi
if [[ -n "$staged_scss_files" ]]
then
    echo "Running Stylelint..."
    ./node_modules/.bin/stylelint $staged_scss_files --stdin --quiet $stylelint_autofix_flag
    stylelint_exit_code=$?
fi
if [ $eslint_exit_code = 0 ] && [ $stylelint_exit_code = 0 ]
then
    add_files_to_staged_tree "${ts_files_to_add_after_linting[*]} ${scss_files_to_add_after_linting[*]}"
    echo -e "${GREEN} ✔ Eslint and Stylelint did not find any errors [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅] ${NC}"
    exit 0
else
    echo -e "${RED} ❌ Linter errors have occurred ( ͡ಥ ͜ʖ ͡ಥ) ${NC}"
    exit 1
fi
