export namespace CONSTANTS {
  export const TAG_PREFIX = 'kk';
  export const ENUM_DELIMITER = '_';
  export const COMPONENT_TAG_DELIMITER = '-';
  export const TRANSITION_DURATION_DEFAULT = 250;
  export const TRANSITION_DURATION_SUPER_FAST = TRANSITION_DURATION_DEFAULT * 0.25;
  export const TRANSITION_DURATION_FAST = TRANSITION_DURATION_DEFAULT * 0.5;
  export const TRANSITION_DURATION_LONG = TRANSITION_DURATION_DEFAULT * 2;
  export const TRANSITION_DURATION_SUPER_LONG = TRANSITION_DURATION_DEFAULT * 3;
}
